#!/bin/bash
#SBATCH -J GATTO_PubMed
#SBATCH -o GATTO_PubMed_%j.out
#SBATCH -e GATTO_PubMed_%j.err
#SBATCH --mail-user francesco.biscacciacarrara@studenti.unipd.it
#SBATCH --mail-type ALL
#SBATCH -n 8
#SBATCH -p allgroups
#SBATCH -t 02:00:00
#SBATCH --mem 30G

cd $SLURM_SUBMIT_DIR

singularity exec --nv --pwd ../code --bind ../code:/code ../python3.8.10.sif python3 FeaturesBuilder.py -d PubMedDiabetes -p $SLURM_NTASKS
