#!/bin/bash
#SBATCH -J GATTO_PubMed_G-0
#SBATCH -o GATTO_PubMed_G-0_%j.out
#SBATCH -e GATTO_PubMed_G-0_%j.err
#SBATCH --mail-user francesco.biscacciacarrara@studenti.unipd.it
#SBATCH --mail-type ALL
#SBATCH -n 32
#SBATCH -p allgroups
#SBATCH -t 04:30:00
#SBATCH --mem 100G

cd $SLURM_SUBMIT_DIR

singularity exec --nv --pwd ../code --bind ../code:/code ../python3.8.10.sif python3 GAT.py -d PubMedDiabetes -p $SLURM_NTASKS
